// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: route_guide.proto

package routeguide

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_guide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_route_guide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_route_guide_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Sum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Z int32 `protobuf:"varint,1,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Sum) Reset() {
	*x = Sum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_guide_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sum) ProtoMessage() {}

func (x *Sum) ProtoReflect() protoreflect.Message {
	mi := &file_route_guide_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sum.ProtoReflect.Descriptor instead.
func (*Sum) Descriptor() ([]byte, []int) {
	return file_route_guide_proto_rawDescGZIP(), []int{1}
}

func (x *Sum) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type X struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
}

func (x *X) Reset() {
	*x = X{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_guide_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X) ProtoMessage() {}

func (x *X) ProtoReflect() protoreflect.Message {
	mi := &file_route_guide_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X.ProtoReflect.Descriptor instead.
func (*X) Descriptor() ([]byte, []int) {
	return file_route_guide_proto_rawDescGZIP(), []int{2}
}

func (x *X) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

type Y struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Y int32 `protobuf:"varint,1,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Y) Reset() {
	*x = Y{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_guide_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Y) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Y) ProtoMessage() {}

func (x *Y) ProtoReflect() protoreflect.Message {
	mi := &file_route_guide_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Y.ProtoReflect.Descriptor instead.
func (*Y) Descriptor() ([]byte, []int) {
	return file_route_guide_proto_rawDescGZIP(), []int{3}
}

func (x *Y) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_route_guide_proto protoreflect.FileDescriptor

var file_route_guide_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65, 0x22,
	0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x79, 0x22, 0x13, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x7a,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x7a, 0x22, 0x11, 0x0a, 0x01, 0x58, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x22, 0x11, 0x0a, 0x01,
	0x59, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x32,
	0xae, 0x01, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x47, 0x75, 0x69, 0x64, 0x65, 0x12, 0x2e,
	0x0a, 0x06, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x12, 0x11, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x0f, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x10, 0x67, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x12, 0x11, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x1a, 0x0f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69,
	0x64, 0x65, 0x2e, 0x53, 0x75, 0x6d, 0x22, 0x00, 0x28, 0x01, 0x12, 0x34, 0x0a, 0x10, 0x67, 0x65,
	0x74, 0x59, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d,
	0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x58, 0x1a, 0x0d, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x59, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x61, 0x72, 0x69, 0x6f, 0x62, 0x65, 0x6e, 0x69, 0x73, 0x73, 0x69, 0x6d, 0x6f, 0x2f, 0x6d, 0x79,
	0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x67, 0x75, 0x69, 0x64,
	0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x67, 0x75, 0x69, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_route_guide_proto_rawDescOnce sync.Once
	file_route_guide_proto_rawDescData = file_route_guide_proto_rawDesc
)

func file_route_guide_proto_rawDescGZIP() []byte {
	file_route_guide_proto_rawDescOnce.Do(func() {
		file_route_guide_proto_rawDescData = protoimpl.X.CompressGZIP(file_route_guide_proto_rawDescData)
	})
	return file_route_guide_proto_rawDescData
}

var file_route_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_route_guide_proto_goTypes = []interface{}{
	(*Point)(nil), // 0: routeguide.Point
	(*Sum)(nil),   // 1: routeguide.Sum
	(*X)(nil),     // 2: routeguide.X
	(*Y)(nil),     // 3: routeguide.Y
}
var file_route_guide_proto_depIdxs = []int32{
	0, // 0: routeguide.RouteGuide.getSum:input_type -> routeguide.Point
	0, // 1: routeguide.RouteGuide.getSumFromPoints:input_type -> routeguide.Point
	2, // 2: routeguide.RouteGuide.getYFromFunction:input_type -> routeguide.X
	1, // 3: routeguide.RouteGuide.getSum:output_type -> routeguide.Sum
	1, // 4: routeguide.RouteGuide.getSumFromPoints:output_type -> routeguide.Sum
	3, // 5: routeguide.RouteGuide.getYFromFunction:output_type -> routeguide.Y
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_route_guide_proto_init() }
func file_route_guide_proto_init() {
	if File_route_guide_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_route_guide_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_guide_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_guide_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_guide_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Y); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_route_guide_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_route_guide_proto_goTypes,
		DependencyIndexes: file_route_guide_proto_depIdxs,
		MessageInfos:      file_route_guide_proto_msgTypes,
	}.Build()
	File_route_guide_proto = out.File
	file_route_guide_proto_rawDesc = nil
	file_route_guide_proto_goTypes = nil
	file_route_guide_proto_depIdxs = nil
}
